### ISSUE TITLE
First line of function code not processed

### ISSUE THREAD

**Issue by cyborg-x1** [synapticon/Synapticon-Coding-Style-Guide#5]
clang (sometimes?) does not process the first line of code of a function.

**Comment by Minipada** [comment]
Was a typo on the script which missed an `\`. It was in fact ignoring everything after `[[combinable]]` and `[[ordered]]` until it reached another XMOS related keyword (`:>`, `<:`, `[[combinable]]` and `[[ordered]]`)
Please update locally your script following the [wiki](https://github.com/synapticon/Synapticon-Coding-Style-Guide/wiki/Beautify-SOMANET-code-via-XTimeComposer).
